import jsPDF from "jspdf";
import { Download } from "lucide-react";

const DownloadPDF = ({ plan }) => {
  const downloadPDF = () => {
    const pdf = new jsPDF();

    const pageWidth = pdf.internal.pageSize.getWidth();
    let y = 20;

    // =========================
    // HEADER
    // =========================

    pdf.setFillColor(13, 71, 161);
    pdf.rect(0, 0, pageWidth, 35, "F");

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.setFont("helvetica", "bold");
    pdf.text("AI Smart Travel Plan", 20, 22);

    pdf.setFontSize(10);
    pdf.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 30);

    pdf.setTextColor(0, 0, 0);

    y = 50;

    // =========================
    // TRIP DETAILS BOX
    // =========================

    pdf.setDrawColor(220, 220, 220);
    pdf.roundedRect(15, y, 180, 50, 3, 3);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Trip Overview", 20, y + 10);

    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");

    pdf.text(`From: ${plan.source}`, 20, y + 18);
    pdf.text(`Destination: ${plan.destination}`, 105, y + 18);

    pdf.text(`Trip Type: ${plan.tripType}`, 20, y + 30);
    pdf.text(`Travelers: ${plan.travelers}`, 105, y + 30);

    pdf.text(`Duration: ${plan.duration}`, 20, y + 42);

    y += 55;

    // =========================
    // SECTION TITLE FUNCTION
    // =========================

    const sectionTitle = (title) => {
      pdf.setDrawColor(13, 71, 161);

      pdf.setLineWidth(0.5);
      pdf.line(20, y, 190, y);

      y += 8;

      pdf.setFontSize(16);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(13, 71, 161);
      pdf.text(title, 20, y);

      pdf.setTextColor(0, 0, 0);

      y += 10;
    };

    // =========================
    // RECOMMENDATIONS
    // =========================

    sectionTitle("Travel Recommendations");

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");

    pdf.text(`Train : ${plan.train}`, 25, y);
    y += 8;
    pdf.text(`Fare : Rs. ${plan.trainFare.replace("₹", "")}`, 35, y);

    y += 12;

    pdf.text(` Bus : ${plan.bus}`, 25, y);
    y += 8;
    pdf.text(` Fare : Rs. ${plan.busFare.replace("₹", "")}`, 35, y);

    y += 12;

    pdf.text(` Hotel : ${plan.hotel}`, 25, y);
    y += 8;
    pdf.text(`Price : Rs. ${plan.hotelPrice.replace("₹", "")}`, 35, y);

    y += 20;

    // =========================
    // DESTINATION INSIGHTS
    // =========================

    sectionTitle("Destination Insights");

    pdf.text(`Best Season : ${plan.bestSeason}`, 25, y);
    y += 10;

    pdf.text(`Weather : ${plan.weather}`, 25, y);

    y += 20;

    // =========================
    // ATTRACTIONS
    // =========================

    sectionTitle("Top Attractions");

    plan.attractions.forEach((place) => {
      pdf.circle(25, y - 1, 1, "F");
      pdf.text(place, 32, y);
      y += 8;
    });

    y += 10;

    // =========================
    // ITINERARY
    // =========================

    sectionTitle("Day Wise Itinerary");

    plan.itinerary.forEach((item, index) => {
      pdf.setFillColor(255, 152, 0);
      pdf.circle(25, y - 1, 2, "F");

      pdf.setFont("helvetica", "bold");
      pdf.text(`Day ${index + 1}`, 32, y);

      y += 7;

      pdf.setFont("helvetica", "normal");

      const lines = pdf.splitTextToSize(item, 145);
      pdf.text(lines, 40, y);

      y += lines.length * 6 + 8;
    });

    y += 10;

    // =========================
    // BUDGET CARD
    // =========================

    pdf.setFillColor(13, 71, 161);
    pdf.roundedRect(15, y, 180, 25, 3, 3, "F");

    pdf.setTextColor(255, 255, 255);

    pdf.setFontSize(12);
    pdf.text("Estimated Trip Budget", 20, y + 10);

    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text(plan.totalCost, 20, y + 20);

    pdf.setTextColor(0, 0, 0);

    // =========================
    // FOOTER
    // =========================

    pdf.setFontSize(10);
    pdf.setTextColor(120, 120, 120);

    pdf.text("Generated by Rail Go AI", 20, 285);

    pdf.text(`Page 1`, pageWidth - 25, 285);

    pdf.save("AI-Smart-Travel-Plan.pdf");
  };

  return (
    <button
      onClick={downloadPDF}
      className="
      flex items-center gap-2
      px-6 h-12
      rounded-xl
      bg-gradient-to-r
      from-orange-500
      to-orange-600
      text-white
      font-semibold
      shadow-lg
      hover:shadow-xl
      transition-all
    "
    >
      <Download size={18} />
      Download PDF
    </button>
  );
};

export default DownloadPDF;
