import AITripForm from "../components/aiTrip/AITripForm";

const AITripPlanner = () => {
  return (
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <div className="relative overflow-hidden rounded-[32px] min-h-[750px]">

        {/* Background Image */}
        <img
          src="/travel-collage.jpg"
          alt="India Travel Destinations"
          className="absolute inset-0 w-full h-full object-cover"
        />

        {/* Dark Gradient Overlay */}
        <div className="absolute inset-0 bg-gradient-to-r from-slate-950/85 via-slate-900/70 to-slate-950/60" />

        {/* Additional Blur Layer */}
        <div className="absolute inset-0 backdrop-[2px]" />

        {/* Content */}
        <div className="relative z-10 p-6 md:p-12 lg:p-16">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 bg-orange-500/90 backdrop-blur-md px-4 py-2 rounded-full text-sm font-semibold shadow-lg">
              ✨ NEW AI FEATURE
            </div>

            <h1 className="mt-6 text-4xl md:text-6xl font-extrabold leading-tight text-white">
              Plan Your Complete
              <span className="block text-orange-400">
                AI Powered Journey
              </span>
            </h1>

            <p className="mt-1 text-lg md:text-xl text-slate-200 max-w-2xl">
              Discover trains, buses, hotels, attractions and get a complete
              day-wise itinerary generated by AI in seconds.
            </p>
          </div>

          {/* Glassmorphism Form */}
          <div className="mt-10 max-w-5xl">
            <AITripForm />
            
          </div>
        </div>
      </div>
    </section>
  );
};

export default AITripPlanner;